## URLs

orangeHrm = https://opensource-demo.orangehrmlive.com/web/index.php/auth/login



==== Authentication Suite Excel-Paths Configuration ====
authentication.workbook = Authentication-Suite.xlsx

<!-- Sheet Names -->
authentication.ValidLoginCreds.Sheet = ValidLoginCreds



==== Admin Suite Excel-Paths Configuration ====
admin.workbook = Admin-Suite.xlsx

<!-- Sheet Names -->
admin.createUserRole.Sheet = AddUser


