##Login Page Locators
loginPage.username = //input[@name='username']
loginPage.password = //input[@name='password']
loginPage.loginButton = //button[@type='submit']

##Admin Page Locators
adminPage.adminTab = //span[text()='Admin']

adminPage.adminHeading = //h6[text()="Admin"]
